"""The canonical generate sequence, shared by the CLI and the release bump.

Both `python3 scripts/skills.py generate` and the release bump
(`scripts/bump_version.py`) must regenerate the SAME artifacts in the SAME
order. Keeping that sequence in one place is load-bearing: when it lived in two
hand-maintained copies they drifted, and the release copy silently dropped the
per-skill asset sync (`ensure_codex_metadata`). A release then regenerated
everything except the bundled icons and failed its own `validate` step on
"Stale 'assets/databricks.png'". One function, one ordering, no drift.

Ordering invariants (do not reorder without re-reading these):
- `ensure_codex_metadata` runs FIRST: it syncs each skill's icons +
  `agents/openai.yaml`, which `generate_manifest` records and `generate_bundle`
  copies. A stale sync here taints both.
- `generate_bundle` runs LAST: it copies `skills/`, `hooks/`, `commands/`,
  `rules/`, `assets/` plus the routing/hook wiring generated by the steps above.
"""

from pathlib import Path

from skillsgen.bundle import generate_bundle
from skillsgen.common import load_meta
from skillsgen.discovery import ensure_codex_metadata
from skillsgen.hooks import generate_hooks
from skillsgen.manifest import generate_manifest, serialize_manifest
from skillsgen.plugins import generate_plugins
from skillsgen.routing import generate_routing


def generate_all(repo_root: Path, version_override: str | None = None) -> dict:
    """Regenerate every artifact from source; return per-step counts + manifest.

    Pass `version_override` to stamp a specific version into the generated
    output (the release bump passes `next_version`); otherwise the version is
    resolved from `version.meta.json` via `load_meta`. The returned dict carries
    the file count for each step plus the manifest object, so callers can print
    their own progress without re-deriving anything.
    """
    written_assets = ensure_codex_metadata(repo_root)

    meta = load_meta(repo_root)
    if version_override is not None:
        meta["version"] = version_override

    written_plugins = generate_plugins(repo_root, meta)
    written_routing = generate_routing(repo_root, meta)
    written_hooks = generate_hooks(repo_root, meta)

    manifest = generate_manifest(repo_root)
    (repo_root / "manifest.json").write_text(serialize_manifest(manifest))

    # LAST: copies the source dirs plus the wiring/routing generated above.
    written_bundle = generate_bundle(repo_root, meta)

    return {
        "assets": written_assets,
        "plugins": written_plugins,
        "routing": written_routing,
        "hooks": written_hooks,
        "bundle": written_bundle,
        "manifest": manifest,
    }
